apiVersion: apps/v1
kind: Deployment
metadata:
  name: orca-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orca-postgres
  template:
    metadata:
      labels:
        app: orca-postgres
    spec:
      containers:
        - name: orca-postgres
          image: postgres:13.3
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
