apiVersion: v1
kind: Service
metadata:
  name: orca-postgres
  labels:
    app: orca-postgres
spec:
  type: NodePort
  ports:
  - name: postgres-node-port
    port: 5432
    nodePort: 31980
  selector:
   app: orca-postgres
