apiVersion: v1
kind: Service
metadata:
  name: orca-service
  labels:
    app: orca-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 30301
  selector:
   app: orca-service
