apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcp-volume
spec:
  storageClassName: local-storage
  hostPath:
    path: "[gcp.json volume path]"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
